# Generated by Django 2.0.2 on 2018-02-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_usuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostaatividade',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
