# Generated by Django 2.0.2 on 2018-02-07 02:35

from django.db import migrations, models
import quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20180206_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='codigo',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respostaatividade',
            name='resposta',
            field=quill.fields.RichTextField(),
        ),
    ]
