# Generated by Django 2.0.2 on 2018-02-07 23:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20180206_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1000)),
                ('embedCode', models.CharField(max_length=1000)),
                ('data_entrega', models.DateField(default=datetime.date.today)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turma_acesso', to='principal.Turma')),
            ],
        ),
    ]
