# Generated by Django 2.0.2 on 2018-02-08 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAssistido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('assistido', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_video', to='principal.Usuario')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='principal.Video')),
            ],
        ),
    ]
