# Generated by Django 2.0.2 on 2018-05-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_videoassistido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostaatividade',
            name='resposta',
            field=models.FileField(upload_to=''),
        ),
    ]
