# Generated by Django 2.0.2 on 2018-05-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_auto_20180531_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='individual',
            field=models.BooleanField(default=True),
        ),
    ]
