# Generated by Django 2.0.6 on 2018-09-23 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_atividade_individual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=10000)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividade_grupo', to='principal.Atividade')),
            ],
        ),
    ]
